### ISSUE TITLE
error when running /multimedia yt

### ISSUE THREAD

**Issue by Saraistupid** [Delta2Force/McMultimedia#2]
when I run /multimedia yt (a link here)
I get this error:
`
[WARNING] .... com.sapher.youtubedl.YoutubeDLException: Cannot run program "youtube-dl" (in directory ".ydl"): error=2, No such file or directory

[WARNING] .... at com.sapher.youtubedl.YoutubeDL.execute(YoutubeDL.java:70)

[WARNING] .... at deltatwoforce.mcmultimedia.McMultimedia$1.run(McMultimedia.java:186)

[WARNING] .... at java.lang.Thread.run(Thread.java:813)`
and idk where to download youtube-dl or wtf is that shit

**Comment by Saraistupid** [comment]
btw I'm using server.pro

**Comment by delta2force** [comment]
You need to put YouTube-DL into your PATH environment variable. Server.pro probably won’t let you do that, meaning that you can’t use it. I’m going to try to develop a way around this soon.
